Add files via upload
LibreLabUCM/LiberarFdI pull request #3
Opened 2017-02-23 00:10 UTC by Zildj1an

Primer curso - Fundamentos de Computadores

2017-02-23 00:23 UTC, Akronix requested changes
La guía no está en markdown, como indica el modelo de guía, sino en un pdf (con lo cual no se puede editar luego de forma colaborativa).
Tampoco entiendo muy bien qué significa el archivo "retos"

2017-02-23 00:41 UTC, Zildj1an commented
He modificado el texto, creo que su utilidad se entenderá mejor así. Y ya no hay guía en pdf.

2017-02-23 09:24 UTC, Akronix commented
Hola @Zildj1an gracias por tu interés en contribuir.
La guía estaba muy bien, no podrías pasarla a markdown? Lo mismo se puede convertir a markdown desde el formato que hayas usado para crearla.
Luego, la carpeta de "Computadores" la cambiaría por "Fundamentos de Computadores".
Para otra vez te agradecería (y también como consejo) un nombre más descriptivo en el Pull Request.

2017-02-27 20:28 UTC, Zildj1an commented
Ya he añadido una Guía de Instalación.

2017-02-28 16:47 UTC, Akronix commented
No te gusta [markdown](https://guides.github.com/features/mastering-markdown/), eh?

2017-02-28 17:12 UTC, Zildj1an commented
Esto vale por ahora...

2017-02-28 17:38 UTC, Akronix commented
Bueno, yo lo dejo a decisión de los que están llevando el proyecto @Joncarre @AdriPanG @javimv36 @elzumbi

2017-08-09 19:04 UTC, Sawyer13 commented
Hay una guía que sirve como referencia a seguir.
Pone hacerlo en md (tienes las otras ya subidas como ejemplo, es fácil pasar el txt a md).

2017-08-09 19:04 UTC, closed without merging